### PR TITLE
WIP: Allow customization of IdentityRole/User

### LINKED ISSUE #4: Cannot derive from IdentityUser/IdentityRole
I would like to be able to derive from the IdentityUser and IdentityRole classes to associate more data with them. (This is possible with the EFCore adapter as well)

Currently, this will result in the IoC container bindings to not resolve properly, because it cannot resolve, for example, `IUserStore<IdentityUser>` to `UserStore<ApplicationUser>`, even though `ApplicationUser` is derived from `IdentityUser`.

I can help out with a PR for that if you agree that should be possible.

### PR DESCRIPTION
**Pull request by RianFuro**
UserStore is now generic over TUser and TRole to allow application
specific classes of IdentityUser and IdentityRole.

Replaced the XML mapping file for NHibernate with mapping by code
classes. This allows users to extend from the mapping classes to
provide their own custom mapping for the respective IdentityUser
and IdentityRole classes.

Provided an extension method to NHibernate's configuration class
to easily add the defined mappings to the user's configuration.

Closes #4 

-----

Changes turned out to be rather big. Need to adapt README to reflect new possibilities, but I'd rather only do that after getting green light that everything else is fine :)
Couldn't run the unit tests on a whim since they run against a preconfigured postgres db and I didn't really want to set one up just for that... testing by hand turned out alright, could be I missed something though.

### CODE REVIEW

**Comment by beginor** [comment]
wow, what a huge PR！ I will review it asap, and if all the tests pass, I will release new version to nuget

**Comment by beginor** [comment]
As these table names, I use postgresql, which is not case sensitive， if I flow the default table names，it will be `aspnetuserroles`, `aspnetuserlogins`, this is not easy to read and use,  so I prefer to use `_` to split charater in database。

**Comment by fredericDelaporte** [comment]
> if all the tests pass

Having some CI enabled would be better. @beginor, tell me if you need to have by example AppVeyor activated for running on this repository. (You would of course still need to provide an adequate appveyor.yml file. NHibernate core repository also uses TeamCity and Travis. But we rather avoid adding new builds to the former (TC). And for the later (Travis), I have not checked yet how to add a new repository to it.)

**Comment by beginor** [comment]
An example of appveyor.yml would be great! I have some experience with CI using gitlab, but I am not familiar with AppVeor.

**Comment by beginor** [comment]
@RianFuro Thanks for your pull request! But I will change your mapping by code part to postgres, and I will provide mapping to other database (sql server) later.

**Comment by RianFuro** [comment]
Hmm... I believe the mapping is actually database agnostic, except for the naming convention. Also while we're on the topic of naming, I believe there's an advantage to stick to Microsofts default naming in this case, since it helps people migrating to this package if they so desire. 

I would rather suggest switching to a convention-based approach. FluentNHibernate does that quite nicely and clearly separates the data mapping from naming conventions. However I'm not sure of tying the package to FluentNHibernate is the best idea... Alternatively something like [this](https://gist.github.com/NOtherDev/1569982) would resemble that approach.

As for your specific problem with postgres, it's just that postgres is case-sensitive by default and needs quotes around columns and tables to recognize case-sensitive naming. I would suggest using something like [this](https://manfredlange.blogspot.com/2011/04/fluent-nhibernate-postgresql-and.html?m=1) instead on the consuming side of necessary and keep the mapping as agnostic as possible.
I actually wonder why NHibernate doesn't just quote everything by default as it's much safer, but I digress.

**Comment by fredericDelaporte** [comment]
> I actually wonder why NHibernate doesn't just quote everything by default as it's much safer

Quoting semantic varies between databases. Some gets case sensitive with quoting (Oracle I believe) while others may not (SQL Server case sensitivity on names is not changed by quoting, it only follow the collation of system tables, ...), ... Better let the user explicitly choosing to quote or not (by using back-tilt ( \` ) in mappings for being database agnostic, NHibernate will translate them to target database quoting).

**Comment by fredericDelaporte** [comment]
> I have some experience with CI using gitlab, but I am not familiar with AppVeor. It would be very great if you provide an example of AppVeor, thanks.

There are some such files in NHibernate other repositories:

- [NHibernate-Caches](https://github.com/nhibernate/NHibernate-Caches/blob/5.4.0/appveyor.yml): run tests and build release artifacts, all the logic is in this file. It is a multi-build file: run for two configurations (debug and release) and for two set of tests (net fx and core fx, both under Windows). So that would mean 4 runs but the combination "core fx tests" and "release" is excluded (the build in all cases build all fx, so the release build artifacts for one is enough).
  If you only need NetFx tests, the [5.2.0 version](https://github.com/nhibernate/NHibernate-Caches/blob/5.2.0/appveyor.yml) is quite simpler, AppVeyor being able to handle those tests directly. (Moreover this version was not building release artifacts, it was just testing.)
- [nhibernate-core](https://github.com/nhibernate/nhibernate-core/blob/5.1.3/appveyor.yml): run tests, most of the logic is in a separated ps file. It is a multi-builds file, run for core tests under Windows for four databases. (Core under Linux is tested with Travis, NetFx is tested with TeamCity.)
- [NHibernate.Spatial](https://github.com/nhibernate/NHibernate.Spatial/blob/v5.1.0-pre001/appveyor.yml): I do only know its existence.

I have added this repository to AppVeyor, setup in order to build only branches or PR having an appveyor.yml file. So you can experiment with it in a PR without any consequences. There are more settings that you should be able to access [here](https://ci.appveyor.com/project/nhibernate/nhibernate-aspnetcore-identity/settings) with your GitHub account (selecting NHibernate as account). But normally you should not need to change anything more there, most settings being settable in appveyor.yml (and ignored in the presence of such a file).

**Pull request merged**
